### ISSUE TITLE
Add PascalCase

### ISSUE THREAD

**Issue by doasync** [davesnx/babel-plugin-transform-react-qa-classes#14]
React component usually follows PascalCase naming convention.

> When an element type starts with a lowercase letter, it refers to a built-in component like <div> or <span> and results in a string 'div' or 'span' passed to React.createElement. Types that start with a capital letter like <Foo /> compile to React.createElement(Foo) and correspond to a component defined or imported in your JavaScript file.
>
> We recommend naming components with a capital letter. If you do have a component that starts with a lowercase letter, assign it to a capitalized variable before using it in JSX.

**Comment by davesnx** [comment]
I'm happy to give the ability to create any transformation on the componentName.

Seems like an easy task!

**Comment by davesnx** [comment]
Feel free to add a PR with this change.

**Comment by ruslan-rt** [comment]
Thanks! Could you please update README?

**Comment by doasync** [comment]
Thanks! Could you please update README?

**Comment by davesnx** [comment]
Update the README with what?

**Comment by doasync** [comment]
> Update the README with what?

The format can be: "pascal" (PascalCase)

**Comment by davesnx** [comment]
Sure!
