### ISSUE TITLE
Bump the version on npm to 1.2.0

### ISSUE THREAD

**Issue by chiplay** [davesnx/babel-plugin-transform-react-qa-classes#20]
Hi @davesnx! Thank you for creating this great plugin and sharing it with the world. I also saw that you bumped the version to 1.2.0 to include the styled-components update (which works great 👌), thanks again!

I'm still seeing version 1.1.0 on npm, so I figured I'd create an issue to help track the progress on getting npm up to date. It seems like there are some build/ci changes that were also needed, let me know if there is anything I can do to help out.

**Comment by davesnx** [comment]
Hey @chiplay 

Just fixed the CI and released 1.3.0: https://github.com/davesnx/babel-plugin-transform-react-qa-classes/runs/316982860

Let me know if works well, otherwise I would stop using gh actions and move to circleci and have more control over ci.

Thanks! (and Thanks again for pushing forward)!

**Comment by chiplay** [comment]
@davesnx thanks for the update! I’m new to GH actions, but it looks pretty great. I didn’t see the new 1.3.0 on npm, and after doing a little research, It’s seems like your workflow file might need some tweaks. Check out this article and see how their setup of the npm scripts/tokens differs from what you have: https://techsparx.com/nodejs/tools/publish-github.html

Hopefully that’s helpful. If you don’t have a chance to take a look, I can try to take a stab at a PR with changes to the workflow config next week. 

Thanks! 🍻

**Comment by davesnx** [comment]
Published manually 1.3.1 and fixed the action, next changes would make it automatically.

Thanks @chiplay

**Comment by chiplay** [comment]
@davesnx thanks!
