### ISSUE TITLE
Components wrapped in a forwardRef will not have attribute applied

### ISSUE THREAD

**Issue by tkharuk** [davesnx/babel-plugin-transform-react-qa-classes#42]
Wrapping components with `forwardRef` will prevent `data-qa` attribute from being added.

Example:
```
import React from "react";

const FancyButton = React.forwardRef((props, ref) => (
  <button {...props} ref={ref} />
));

export default FancyButton;
```

will result in a type `ArrowFunctionExpression` with a parent as type `CallExpression`.
Call expression will not have any other parents to pluck the name from.

Maybe it is even impossible to display name for all the possible usages.
Implied from https://reactjs.org/docs/forwarding-refs.html#displaying-a-custom-name-in-devtools

It could be still possible to support forward ref with techniques described in docs ^.

E.g.
```
const WrappedComponent = React.forwardRef(
  function myFunction(props, ref) {
    return <LogProps {...props} forwardedRef={ref} />;
  }
);

export default WrappedComponent;
```

will result in a:
![image](https://user-images.githubusercontent.com/1205052/102224068-2b07c480-3eee-11eb-824a-22767787f5cd.png)

So, theoretically, it is doable for some cases.

**Comment by davesnx** [comment]
Hey @tkharuk, is it doable for sure. I see that there's a workaround that accomplishes the desired behaviour. Abstracting the callback to be a component, and passing it to `forwardRef` would solve the issue meanwhile.

The actual AST transformation would be a little heavy and it might be a big task, I'm currently busy to implement this diff, feel free to open a draft PR I can guide you to merging it.

Thanks for opening the issue.

**Comment by tkharuk** [comment]
Hi @davesnx, I'm not sure I've understood the workaround :(
Can you show a code example, please?
Do you mean it will work with the current version of the plugin with no changes needed?

**Comment by davesnx** [comment]
Abstracting the component to a constant will make the plugin to treat it as a regular component and work as it is. If I'm understanding the issue correctly, this should make it work without any changes to the plugin.

```
import React from "react";

const Button = (props, ref) => <button {...props} ref={ref} />;

const FancyButton = React.forwardRef(Button);

export default FancyButton;
```

**Comment by tkharuk** [comment]
Yes, it is treated as an `ArrowFunctionExpression` and gets a name with no problems.
it will apply a `button` and not a `fancy-button`, which is okay, I suppose.
Thanks a lot!

I think it is worth adding to documentation, wdyt?
I can do it as a mean of paying you for the tip ;)

**Comment by davesnx** [comment]
I mean, it's the right behaviour, we add data-qa to the JSX expressions.
We aren't able to inject the variable name that later is wrapped at run-time, that's an impossible job. 

I wouldn't add this case on the documentation, since there are many use cases that might be affected by this: High order components, forwardRef, styled(). 

Thanks for opening the issue and cool that you found the way to have it working!
