### ISSUE TITLE
Support styled-components?

### ISSUE THREAD

**Issue by davesnx** [davesnx/babel-plugin-transform-react-qa-classes#7]

**Comment by ephetic** [comment]
Adding support for styled-components would be excellent.  The germaine part of their own transform for [better debugging names](https://www.styled-components.com/docs/tooling#better-debugging) is https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L33 wherein they inject a `withConfig` method call:

```
const MyComponent = styled.div`color:red;`
```
becomes
```
const MyComponent = styled.div.withConfig({displayName: ..., componentId: ...})`color:red`;
```

I haven't yet grokked how they're recognizing that `styled.div'color:red;'` is a taggedTemplateExpression that they own.  Also, I don't know if `withConfig` supports injecting attribute names, but styled-components has another method that does: 
```
const MyComponent = styled.div.attrs(attrs => ({'data-qa':'my-component'}))`color:red;`
```

**Comment by davesnx** [comment]
Sweet, I'm re-opening that issue then!

**Comment by ephetic** [comment]
These is what I'm using to detect `styled-components` thus far.  I'll try to get you a PR soon.  I'm only going to try to support when a styled component is an r-value (in direct assignment or return).

```
        {
          const possibleStyledRef = path.node.name
          if (!path.scope.hasBinding(possibleStyledRef)) return

          const binding = path.scope.getBinding(possibleStyledRef)
          if (binding.kind != 'module') return

          const source = binding.path.parent.source.value
          if (source != 'styled-components') return
        }
```

**Comment by davesnx** [comment]
Sweet, I would first implement styled-components and later taking a look to other implementations like emotion!

Thanks!

**Comment by ephetic** [comment]
Cool.  I didn't know [Emotion](https://emotion.sh/docs/styled) and [Glamorous](https://glamorous.rocks/) even existed.  I'll keep that in mind with my factoring.

For future reference:
https://emotion.sh/docs/with-props
https://glamorous.rocks/api/  (see `withProps`)
